chain_id: 5000
agni_pool_job:
  position_token_address: '0x218bf598d1453383e2f4aa7b14ffb9bfb102d637'
  factory_address: '0x25780dc8fc3cfbd75f33bfdab65e969b603b2035'

uniswap_v3_pool_job:
  position_token_address: '0xaaa78e8c4241990b4ce159e105da08129345946a'
  factory_address: '0xaaa32926fce6be95ea2c51cb4fcb60836d320c42'

init_capital_job:
  core_address: '0x972bcb0284cca0152527c4f70f8f689852bcafc5'